/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../components/input-output/input-output';
const styles_InputOutput:any[] = ([] as any[]);
export const RenderType_InputOutput:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_InputOutput,
  data: {}
}
);
export function View_InputOutput_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n              '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      'Counter: ',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n              '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      'Running total of counter values: ',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n              '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      'Growing string: ',
      ''
    ]
    ))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.InputOutput = v.component;
    const currVal_0:any = co.headline;
    ck(v,1,0,currVal_0);
    const currVal_1:any = co.counter;
    ck(v,4,0,currVal_1);
    const currVal_2:any = co.sum;
    ck(v,7,0,currVal_2);
    const currVal_3:any = co.growingString;
    ck(v,10,0,currVal_3);
  });
}
function View_InputOutput_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'input-output',([] as any[]),(null as any),(null as any),(null as any),View_InputOutput_0,RenderType_InputOutput)),
    import0.ɵdid(114688,(null as any),0,import1.InputOutput,[
      import0.ElementRef,
      [
        8,
        (null as any)
      ]

    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const InputOutputNgFactory:import0.ComponentFactory<import1.InputOutput> = import0.ɵccf('input-output',import1.InputOutput,View_InputOutput_Host_0,{
  counter: 'counter',
  fixedValue: 'fixedValue',
  sum: 'mySum',
  headline: 'headline',
  growingString: 'growingString'
}
,{stringChanged: 'stringChanged'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3Rvci9EZXZlbG9wbWVudC9hbmd1bGFyLTItc2FtcGxlcy9jb21wb25lbnRzL2lucHV0LW91dHB1dC9pbnB1dC1vdXRwdXQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvdG9yL0RldmVsb3BtZW50L2FuZ3VsYXItMi1zYW1wbGVzL2NvbXBvbmVudHMvaW5wdXQtb3V0cHV0L2lucHV0LW91dHB1dC50cyIsIm5nOi8vL1VzZXJzL3Rvci9EZXZlbG9wbWVudC9hbmd1bGFyLTItc2FtcGxlcy9jb21wb25lbnRzL2lucHV0LW91dHB1dC9pbnB1dC1vdXRwdXQudHMuSW5wdXRPdXRwdXQuaHRtbCIsIm5nOi8vL1VzZXJzL3Rvci9EZXZlbG9wbWVudC9hbmd1bGFyLTItc2FtcGxlcy9jb21wb25lbnRzL2lucHV0LW91dHB1dC9pbnB1dC1vdXRwdXQudHMuSW5wdXRPdXRwdXRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+e3toZWFkbGluZX19PC9oMT5cbiAgICAgICAgICAgICAgPGRpdj5Db3VudGVyOiB7e2NvdW50ZXJ9fTwvZGl2PlxuICAgICAgICAgICAgICA8ZGl2PlJ1bm5pbmcgdG90YWwgb2YgY291bnRlciB2YWx1ZXM6IHt7c3VtfX08L2Rpdj5cbiAgICAgICAgICAgICAgPGRpdj5Hcm93aW5nIHN0cmluZzoge3tncm93aW5nU3RyaW5nfX08L2Rpdj4iLCI8aW5wdXQtb3V0cHV0PjwvaW5wdXQtb3V0cHV0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJO01BQUE7TUFBQTtJQUFBO0lBQUE7SUFBaUI7SUFDUDtJQUFLO01BQUE7TUFBQTtJQUFBO0lBQUE7SUFBMEI7SUFDL0I7SUFBSztNQUFBO01BQUE7SUFBQTtJQUFBO0lBQThDO0lBQ25EO0lBQUs7TUFBQTtNQUFBO0lBQUE7SUFBQTs7OztJQUhmO0lBQUE7SUFDZTtJQUFBO0lBQ0E7SUFBQTtJQUNBO0lBQUE7Ozs7O0lDSG5CO2dCQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7OztJQUFBOzs7Ozs7Ozs7OyJ9
