/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from '../../../components/access-child-components/child';
const styles_Child:any[] = ([] as any[]);
export const RenderType_Child:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: styles_Child,
  data: {animation: ([] as any[])}
}
);
export function View_Child_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),[
      '',
      ''
    ]
    )
  ]
  ,(null as any),(check,view) => {
    var comp:import1.Child = view.component;
    const currVal_0:any = comp.time;
    check(view,1,0,currVal_0);
  });
}
const RenderType_Child_Host:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {animation: ([] as any[])}
}
);
function View_Child_Host_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),1,'child',([] as any[]),(null as any),(null as any),(null as any),View_Child_0,RenderType_Child),
    import0.ɵdirectiveDef(1024,(null as any),0,import1.Child,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const ChildNgFactory:import0.ComponentFactory<import1.Child> = import0.ɵcreateComponentFactory('child',import1.Child,View_Child_Host_0);