/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../components/access-child-components/parent';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/core/src/linker/query_list';
import * as import11 from '../../../components/access-child-components/child';
import * as import12 from './child.ngfactory';
var renderType_Parent_Host:import0.RenderComponentType = (null as any);
class _View_Parent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Parent_0_4:import3.Parent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Parent_Host0,renderType_Parent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('parent',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Parent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Parent_0_4 = new import3.Parent();
    this._appEl_0.initComponent(this._Parent_0_4,[],compView_0);
    compView_0.create(this._Parent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Parent) && (0 === requestNodeIndex))) { return this._Parent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Parent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_Parent_Host === (null as any))) { (renderType_Parent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_Parent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ParentNgFactory:import9.ComponentFactory<import3.Parent> = new import9.ComponentFactory<import3.Parent>('parent',viewFactory_Parent_Host0,import3.Parent);
const styles_Parent:any[] = [];
var renderType_Parent:import0.RenderComponentType = (null as any);
class _View_Parent0 extends import1.AppView<import3.Parent> {
  _viewQuery_Child_0:import10.QueryList<any>;
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _Child_5_4:import11.Child;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _Child_7_4:import11.Child;
  _text_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Parent0,renderType_Parent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Child_0 = new import10.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Update Time via ViewChildren',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'child',(null as any));
    this._appEl_5 = new import2.AppElement(5,0,this,this._el_5);
    var compView_5:any = import12.viewFactory_Child0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Child_5_4 = new import11.Child();
    this._appEl_5.initComponent(this._Child_5_4,[],compView_5);
    compView_5.create(this._Child_5_4,[],(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'child',(null as any));
    this._appEl_7 = new import2.AppElement(7,0,this,this._el_7);
    var compView_7:any = import12.viewFactory_Child0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Child_7_4 = new import11.Child();
    this._appEl_7.initComponent(this._Child_7_4,[],compView_7);
    compView_7.create(this._Child_7_4,[],(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.Child) && (5 === requestNodeIndex))) { return this._Child_5_4; }
    if (((token === import11.Child) && (7 === requestNodeIndex))) { return this._Child_7_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._viewQuery_Child_0.dirty) {
      this._viewQuery_Child_0.reset([
        this._Child_5_4,
        this._Child_7_4
      ]
      );
      this.context.viewChildren = this._viewQuery_Child_0;
      this._viewQuery_Child_0.notifyOnChanges();
    } }
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.updateViewChildren()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Parent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.Parent> {
  if ((renderType_Parent === (null as any))) { (renderType_Parent = viewUtils.createRenderComponentType('/Users/tor/Development/angular-2-samples/components/access-child-components/parent.ts class Parent - inline template',0,import8.ViewEncapsulation.None,styles_Parent,{})); }
  return new _View_Parent0(viewUtils,parentInjector,declarationEl);
}