/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../components/rxjs-streams/rxjs-streams';
const styles_RxJsStreams:any[] = ([] as any[]);
export const RenderType_RxJsStreams:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: styles_RxJsStreams,
  data: {animation: ([] as any[])}
}
);
function View_RxJsStreams_1():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),6,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n    ']),
      import0.ɵelementDef(0,(null as any),(null as any),3,'div',[[
        'class',
        'floatLeft'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵdirectiveDef(4,(null as any),0,import1.NgClass,[
      import0.IterableDiffers,
      import0.KeyValueDiffers,
      import0.ElementRef,
      import0.Renderer
    ]
    ,{
      klass: [
        0,
        'klass'
      ]
      ,
      ngClass: [
        1,
        'ngClass'
      ]

    }
    ,(null as any)),
    import0.ɵpureObjectDef([
      'stream1',
      'stream2'
    ]
    ),
    import0.ɵtextDef((null as any),[
      '',
      ''
    ]
    ),
    import0.ɵtextDef((null as any),['\n  '])
  ]
  ,(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = 'floatLeft';
    const currVal_1:any = check(view,4,0,(view.context.$implicit.source === 1),(view.context.$implicit.source === 2));
    check(view,3,0,currVal_0,currVal_1);
  },(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = view.context.$implicit.value;
    check(view,5,0,currVal_0);
  });
}
function View_RxJsStreams_2():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),6,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n    ']),
      import0.ɵelementDef(0,(null as any),(null as any),3,'div',[[
        'class',
        'floatLeft'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵdirectiveDef(4,(null as any),0,import1.NgClass,[
      import0.IterableDiffers,
      import0.KeyValueDiffers,
      import0.ElementRef,
      import0.Renderer
    ]
    ,{
      klass: [
        0,
        'klass'
      ]
      ,
      ngClass: [
        1,
        'ngClass'
      ]

    }
    ,(null as any)),
    import0.ɵpureObjectDef([
      'stream1',
      'stream2'
    ]
    ),
    import0.ɵtextDef((null as any),[
      '',
      ''
    ]
    ),
    import0.ɵtextDef((null as any),['\n  '])
  ]
  ,(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = 'floatLeft';
    const currVal_1:any = check(view,4,0,(view.context.$implicit.source === 1),(view.context.$implicit.source === 2));
    check(view,3,0,currVal_0,currVal_1);
  },(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = view.context.$implicit.value;
    check(view,5,0,currVal_0);
  });
}
function View_RxJsStreams_3():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),6,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n    ']),
    import0.ɵelementDef(0,(null as any),(null as any),3,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵdirectiveDef(4,(null as any),0,import1.NgClass,[
      import0.IterableDiffers,
      import0.KeyValueDiffers,
      import0.ElementRef,
      import0.Renderer
    ]
      ,{ngClass: [
        0,
        'ngClass'
      ]
    },(null as any)),
    import0.ɵpureObjectDef([
      'stream1',
      'stream2'
    ]
    ),
    import0.ɵtextDef((null as any),[
      '',
      ''
    ]
    ),
    import0.ɵtextDef((null as any),['\n  '])
  ]
  ,(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = check(view,4,0,(view.context.$implicit.source === 1),(view.context.$implicit.source === 2));
    check(view,3,0,currVal_0);
  },(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = view.context.$implicit.value;
    check(view,5,0,currVal_0);
  });
}
export function View_RxJsStreams_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
      import0.ɵelementDef(0,(null as any),(null as any),1,'div',[[
        'class',
        'stream1'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Stream1']),
    import0.ɵtextDef((null as any),['\n']),
      import0.ɵelementDef(0,(null as any),(null as any),1,'div',[[
        'class',
        'stream2'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Stream2']),
    import0.ɵtextDef((null as any),['\n']),
    import0.ɵelementDef(0,(null as any),(null as any),0,'br',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n']),
      import0.ɵelementDef(0,(null as any),(null as any),1,'button',([] as any[]),(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.RxJsStreams = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>comp.mergeStreams()) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Merge Streams']),
    import0.ɵtextDef((null as any),['\n']),
      import0.ɵelementDef(0,(null as any),(null as any),1,'button',([] as any[]),(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.RxJsStreams = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>comp.concatStreams()) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Concat Streams']),
    import0.ɵtextDef((null as any),['\n']),
      import0.ɵelementDef(0,(null as any),(null as any),1,'button',([] as any[]),(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.RxJsStreams = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>comp.forkJoinStreams()) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵtextDef((null as any),['ForkJoin Streams']),
    import0.ɵtextDef((null as any),['\n']),
      import0.ɵelementDef(0,(null as any),(null as any),1,'button',([] as any[]),(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.RxJsStreams = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>comp.flatMapStreams()) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵtextDef((null as any),['FlatMap Streams']),
    import0.ɵtextDef((null as any),['\n\n']),
      import0.ɵelementDef(0,(null as any),(null as any),7,'div',[[
        'class',
        'stream-section'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n  ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'h4',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Concatenated Streams']),
    import0.ɵtextDef((null as any),['\n  ']),
    import0.ɵanchorDef(256,(null as any),(null as any),1,(null as any),View_RxJsStreams_1),
    import0.ɵdirectiveDef(12,(null as any),0,import1.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    import0.ɵtextDef((null as any),['\n']),
    import0.ɵtextDef((null as any),['\n\n']),
      import0.ɵelementDef(0,(null as any),(null as any),7,'div',[[
        'class',
        'stream-section'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n  ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'h4',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Merged Streams']),
    import0.ɵtextDef((null as any),['\n  ']),
    import0.ɵanchorDef(256,(null as any),(null as any),1,(null as any),View_RxJsStreams_2),
    import0.ɵdirectiveDef(12,(null as any),0,import1.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    import0.ɵtextDef((null as any),['\n']),
    import0.ɵtextDef((null as any),['\n\n']),
      import0.ɵelementDef(0,(null as any),(null as any),7,'div',[[
        'class',
        'stream-section'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n  ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'h4',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['ForkJoined Streams']),
    import0.ɵtextDef((null as any),['\n  ']),
    import0.ɵanchorDef(256,(null as any),(null as any),1,(null as any),View_RxJsStreams_3),
    import0.ɵdirectiveDef(12,(null as any),0,import1.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    import0.ɵtextDef((null as any),['\n']),
    import0.ɵtextDef((null as any),['\n\n']),
    import0.ɵelementDef(0,(null as any),(null as any),0,'br',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n']),
    import0.ɵelementDef(0,(null as any),(null as any),7,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n  ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'h4',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Flatmapped Streams']),
    import0.ɵtextDef((null as any),['\n  ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),[
      '',
      ''
    ]
    ),
    import0.ɵtextDef((null as any),['\n']),
    import0.ɵtextDef((null as any),['\n\n'])
  ]
  ,(check,view) => {
    var comp:import2.RxJsStreams = view.component;
    const currVal_0:any = comp.concatStream;
    check(view,26,0,currVal_0);
    const currVal_1:any = comp.mergeStream;
    check(view,35,0,currVal_1);
    const currVal_2:any = comp.forkJoinStream;
    check(view,44,0,currVal_2);
  },(check,view) => {
    var comp:import2.RxJsStreams = view.component;
    const currVal_0:any = comp.flatMappedStreams.msg;
    check(view,55,0,currVal_0);
  });
}
const RenderType_RxJsStreams_Host:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {animation: ([] as any[])}
}
);
function View_RxJsStreams_Host_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),1,'rxjs-streams',([] as any[]),(null as any),(null as any),(null as any),View_RxJsStreams_0,RenderType_RxJsStreams),
    import0.ɵdirectiveDef(1024,(null as any),0,import2.RxJsStreams,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const RxJsStreamsNgFactory:import0.ComponentFactory<import2.RxJsStreams> = import0.ɵcreateComponentFactory('rxjs-streams',import2.RxJsStreams,View_RxJsStreams_Host_0);