/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './survey.ngfactory';
import * as import2 from '../../../components/survey/survey';
import * as import3 from '../../../components/survey/survey-demo';
const styles_SurveyDemo:any[] = ([] as any[]);
export const RenderType_SurveyDemo:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_SurveyDemo,
  data: {}
}
);
export function View_SurveyDemo_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Survey using Dynamic Form'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'survey',([] as any[]),(null as any),(null as any),(null as any),import1.View_Survey_0,import1.RenderType_Survey)),
      import0.ɵdid(57344,(null as any),0,import2.Survey,([] as any[]),{model: [
        0,
        'model'
      ]
    },(null as any))
  ]
  ,(ck,v) => {
    var co:import3.SurveyDemo = v.component;
    const currVal_0:any = co.questionModel;
    ck(v,4,0,currVal_0);
  },(null as any));
}
function View_SurveyDemo_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'survey-demo',([] as any[]),(null as any),(null as any),(null as any),View_SurveyDemo_0,RenderType_SurveyDemo)),
    import0.ɵdid(24576,(null as any),0,import3.SurveyDemo,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const SurveyDemoNgFactory:import0.ComponentFactory<import3.SurveyDemo> = import0.ɵccf('survey-demo',import3.SurveyDemo,View_SurveyDemo_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3Rvci9EZXZlbG9wbWVudC9hbmd1bGFyLTItc2FtcGxlcy9jb21wb25lbnRzL3N1cnZleS9zdXJ2ZXktZGVtby5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy90b3IvRGV2ZWxvcG1lbnQvYW5ndWxhci0yLXNhbXBsZXMvY29tcG9uZW50cy9zdXJ2ZXkvc3VydmV5LWRlbW8udHMiLCJuZzovLy9Vc2Vycy90b3IvRGV2ZWxvcG1lbnQvYW5ndWxhci0yLXNhbXBsZXMvY29tcG9uZW50cy9zdXJ2ZXkvc3VydmV5LWRlbW8udHMuU3VydmV5RGVtby5odG1sIiwibmc6Ly8vVXNlcnMvdG9yL0RldmVsb3BtZW50L2FuZ3VsYXItMi1zYW1wbGVzL2NvbXBvbmVudHMvc3VydmV5L3N1cnZleS1kZW1vLnRzLlN1cnZleURlbW9fSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2PjxoMT5TdXJ2ZXkgdXNpbmcgRHluYW1pYyBGb3JtPC9oMT48c3VydmV5IFttb2RlbF09XCJxdWVzdGlvbk1vZGVsXCI+PC9zdXJ2ZXk+PC9kaXY+IiwiPHN1cnZleS1kZW1vPjwvc3VydmV5LWRlbW8+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFBSztJQUFJO0lBQThCO2tCQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7Ozs7SUFBUTtJQUFSLFNBQVEsU0FBUjs7Ozs7SUNBdkM7Z0JBQUE7Ozs7In0=
