/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../components/bound-textbox/bound-textbox';
const styles_BoundTextbox:any[] = ([] as any[]);
export const RenderType_BoundTextbox:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_BoundTextbox,
  data: {}
}
);
export function View_BoundTextbox_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Bound Textbox'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),0,'input',([] as any[]),[[
        8,
        'value',
        0
      ]
      ],[[
        (null as any),
        'keyup'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.BoundTextbox = v.component;
      if (('keyup' === en)) {
        const pd_0:any = ((<any>co.typing($event)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'span',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    ))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.BoundTextbox = v.component;
    const currVal_0:any = co.text;
    ck(v,2,0,currVal_0);
    const currVal_1:any = co.text;
    ck(v,4,0,currVal_1);
  });
}
function View_BoundTextbox_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'bound-textbox',([] as any[]),(null as any),(null as any),(null as any),View_BoundTextbox_0,RenderType_BoundTextbox)),
    import0.ɵdid(24576,(null as any),0,import1.BoundTextbox,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const BoundTextboxNgFactory:import0.ComponentFactory<import1.BoundTextbox> = import0.ɵccf('bound-textbox',import1.BoundTextbox,View_BoundTextbox_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3Rvci9EZXZlbG9wbWVudC9hbmd1bGFyLTItc2FtcGxlcy9jb21wb25lbnRzL2JvdW5kLXRleHRib3gvYm91bmQtdGV4dGJveC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy90b3IvRGV2ZWxvcG1lbnQvYW5ndWxhci0yLXNhbXBsZXMvY29tcG9uZW50cy9ib3VuZC10ZXh0Ym94L2JvdW5kLXRleHRib3gudHMiLCJuZzovLy9Vc2Vycy90b3IvRGV2ZWxvcG1lbnQvYW5ndWxhci0yLXNhbXBsZXMvY29tcG9uZW50cy9ib3VuZC10ZXh0Ym94L2JvdW5kLXRleHRib3gudHMuQm91bmRUZXh0Ym94Lmh0bWwiLCJuZzovLy9Vc2Vycy90b3IvRGV2ZWxvcG1lbnQvYW5ndWxhci0yLXNhbXBsZXMvY29tcG9uZW50cy9ib3VuZC10ZXh0Ym94L2JvdW5kLXRleHRib3gudHMuQm91bmRUZXh0Ym94X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPkJvdW5kIFRleHRib3g8L2gxPjxpbnB1dCBbdmFsdWVdPVwidGV4dFwiIChrZXl1cCk9XCJ0eXBpbmcoJGV2ZW50KVwiIC8+PHNwYW4+e3t0ZXh0fX08L3NwYW4+IiwiPGJvdW5kLXRleHRib3g+PC9ib3VuZC10ZXh0Ym94PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJO01BQWtCO1FBQUE7UUFBQTtRQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7TUFBQTtNQUFzQjtRQUFBO1FBQUE7TUFBQTtNQUF0QjtJQUFBO0lBQWlEO0lBQU07TUFBQTtNQUFBO0lBQUE7SUFBQTs7OztJQUFoRDtJQUFQLFNBQU8sU0FBUDtJQUF1RDtJQUFBOzs7OztJQ0E3RTtnQkFBQTs7OzsifQ==
