/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from '../../../components/log-tail/log-demo';
import * as import2 from '@angular/forms';
import * as import3 from '@angular/common';
import * as import4 from '../../../components/log-tail/store';
import * as import5 from '../../../components/log-tail/log-tail-service';
import * as import6 from '@angular/http';
const styles_LogDemo:any[] = ([] as any[]);
export const RenderType_LogDemo:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: styles_LogDemo,
  data: {animation: ([] as any[])}
}
);
function View_LogDemo_1():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),7,'tr',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n                        ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'td',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),[
      '',
      ''
    ]
    ),
    import0.ɵtextDef((null as any),['\n                        ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'td',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),[
      '',
      ''
    ]
    ),
    import0.ɵtextDef((null as any),['\n                     '])
  ]
  ,(null as any),(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = view.context.$implicit.text;
    check(view,3,0,currVal_0);
    const currVal_1:any = view.context.$implicit.severity;
    check(view,6,0,currVal_1);
  });
}
export function View_LogDemo_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),44,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n                ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Error log state managed using Redux']),
    import0.ɵtextDef((null as any),['\n                ']),
      import0.ɵelementDef(0,(null as any),(null as any),1,'button',[[
        'style',
        'margin-bottom: 10px;'
      ]
      ],(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import1.LogDemo = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>comp.generateLogEntry()) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Add new log entry']),
    import0.ɵtextDef((null as any),['\n                ']),
    import0.ɵelementDef(0,(null as any),(null as any),5,'input',[
      [
        'placeholder',
        'message'
      ]
      ,
      [
        'type',
        'text'
      ]

    ]
    ,[
      [
        1,
        'ng-untouched'
      ]
      ,
      [
        1,
        'ng-touched'
      ]
      ,
      [
        1,
        'ng-pristine'
      ]
      ,
      [
        1,
        'ng-dirty'
      ]
      ,
      [
        1,
        'ng-valid'
      ]
      ,
      [
        1,
        'ng-invalid'
      ]
      ,
      [
        1,
        'ng-pending'
      ]

    ]
    ,[
      [
        (null as any),
        'ngModelChange'
      ]
      ,
      [
        (null as any),
        'input'
      ]
      ,
      [
        (null as any),
        'blur'
      ]
      ,
      [
        (null as any),
        'compositionstart'
      ]
      ,
      [
        (null as any),
        'compositionend'
      ]

    ]
    ,(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import1.LogDemo = view.component;
      if (('input' === eventName)) {
        const pd_0:any = ((<any>import0.ɵnodeValue(view,9).onChange($event.target.value)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      if (('blur' === eventName)) {
        const pd_1:any = ((<any>import0.ɵnodeValue(view,9).onTouched()) !== false);
        allowDefault = (pd_1 && allowDefault);
      }
      if (('compositionstart' === eventName)) {
        const pd_2:any = ((<any>import0.ɵnodeValue(view,11).compositionStart()) !== false);
        allowDefault = (pd_2 && allowDefault);
      }
      if (('compositionend' === eventName)) {
        const pd_3:any = ((<any>import0.ɵnodeValue(view,11).compositionEnd()) !== false);
        allowDefault = (pd_3 && allowDefault);
      }
      if (('ngModelChange' === eventName)) {
        const pd_4:any = ((<any>(comp.msg = $event)) !== false);
        allowDefault = (pd_4 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵdirectiveDef(0,(null as any),0,import2.DefaultValueAccessor,[
      import0.Renderer,
      import0.ElementRef
    ]
    ,(null as any),(null as any)),
    import0.ɵproviderDef(0,(null as any),2,import2.NG_VALUE_ACCESSOR,(p0_0:any) => {
      return [p0_0];
    },[import2.DefaultValueAccessor]),
    import0.ɵdirectiveDef(10,(null as any),0,import2.NgModel,[
      [
        8,
        (null as any)
      ]
      ,
      [
        8,
        (null as any)
      ]
      ,
      [
        8,
        (null as any)
      ]
      ,
      [
        2,
        import2.NG_VALUE_ACCESSOR
      ]

    ]
      ,{model: [
        0,
        'model'
      ]
    },{update: 'ngModelChange'}),
    import0.ɵproviderDef(0,(null as any),3,import2.NgControl,(null as any),[import2.NgModel]),
    import0.ɵdirectiveDef(0,(null as any),0,import2.NgControlStatus,[import2.NgControl],(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n                ']),
    import0.ɵelementDef(0,(null as any),(null as any),6,'input',[
      [
        'placeholder',
        'severity'
      ]
      ,
      [
        'type',
        'number'
      ]

    ]
    ,[
      [
        1,
        'ng-untouched'
      ]
      ,
      [
        1,
        'ng-touched'
      ]
      ,
      [
        1,
        'ng-pristine'
      ]
      ,
      [
        1,
        'ng-dirty'
      ]
      ,
      [
        1,
        'ng-valid'
      ]
      ,
      [
        1,
        'ng-invalid'
      ]
      ,
      [
        1,
        'ng-pending'
      ]

    ]
    ,[
      [
        (null as any),
        'ngModelChange'
      ]
      ,
      [
        (null as any),
        'input'
      ]
      ,
      [
        (null as any),
        'blur'
      ]
      ,
      [
        (null as any),
        'change'
      ]
      ,
      [
        (null as any),
        'compositionstart'
      ]
      ,
      [
        (null as any),
        'compositionend'
      ]

    ]
    ,(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import1.LogDemo = view.component;
      if (('input' === eventName)) {
        const pd_0:any = ((<any>import0.ɵnodeValue(view,16).onChange($event.target.value)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      if (('blur' === eventName)) {
        const pd_1:any = ((<any>import0.ɵnodeValue(view,16).onTouched()) !== false);
        allowDefault = (pd_1 && allowDefault);
      }
      if (('change' === eventName)) {
        const pd_2:any = ((<any>import0.ɵnodeValue(view,17).onChange($event.target.value)) !== false);
        allowDefault = (pd_2 && allowDefault);
      }
      if (('input' === eventName)) {
        const pd_3:any = ((<any>import0.ɵnodeValue(view,17).onChange($event.target.value)) !== false);
        allowDefault = (pd_3 && allowDefault);
      }
      if (('blur' === eventName)) {
        const pd_4:any = ((<any>import0.ɵnodeValue(view,17).onTouched()) !== false);
        allowDefault = (pd_4 && allowDefault);
      }
      if (('compositionstart' === eventName)) {
        const pd_5:any = ((<any>import0.ɵnodeValue(view,19).compositionStart()) !== false);
        allowDefault = (pd_5 && allowDefault);
      }
      if (('compositionend' === eventName)) {
        const pd_6:any = ((<any>import0.ɵnodeValue(view,19).compositionEnd()) !== false);
        allowDefault = (pd_6 && allowDefault);
      }
      if (('ngModelChange' === eventName)) {
        const pd_7:any = ((<any>(comp.severity = $event)) !== false);
        allowDefault = (pd_7 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵdirectiveDef(0,(null as any),0,import2.DefaultValueAccessor,[
      import0.Renderer,
      import0.ElementRef
    ]
    ,(null as any),(null as any)),
    import0.ɵdirectiveDef(0,(null as any),0,import2.ɵbc,[
      import0.Renderer,
      import0.ElementRef
    ]
    ,(null as any),(null as any)),
    import0.ɵproviderDef(0,(null as any),2,import2.NG_VALUE_ACCESSOR,(p0_0:any,p1_0:any) => {
      return [
        p0_0,
        p1_0
      ]
      ;
    },[
      import2.DefaultValueAccessor,
      import2.ɵbc
    ]
    ),
    import0.ɵdirectiveDef(10,(null as any),0,import2.NgModel,[
      [
        8,
        (null as any)
      ]
      ,
      [
        8,
        (null as any)
      ]
      ,
      [
        8,
        (null as any)
      ]
      ,
      [
        2,
        import2.NG_VALUE_ACCESSOR
      ]

    ]
      ,{model: [
        0,
        'model'
      ]
    },{update: 'ngModelChange'}),
    import0.ɵproviderDef(0,(null as any),3,import2.NgControl,(null as any),[import2.NgModel]),
    import0.ɵdirectiveDef(0,(null as any),0,import2.NgControlStatus,[import2.NgControl],(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n                ']),
      import0.ɵelementDef(0,(null as any),(null as any),16,'table',[[
        'class',
        'table'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n                     ']),
    import0.ɵelementDef(0,(null as any),(null as any),14,'tbody',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵelementDef(0,(null as any),(null as any),8,'tr',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n                        ']),
    import0.ɵelementDef(0,(null as any),(null as any),2,'td',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵelementDef(0,(null as any),(null as any),1,'strong',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Message']),
    import0.ɵelementDef(0,(null as any),(null as any),2,'td',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵelementDef(0,(null as any),(null as any),1,'strong',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Severity']),
    import0.ɵtextDef((null as any),['\n                     ']),
    import0.ɵtextDef((null as any),['\n                     ']),
    import0.ɵanchorDef(256,(null as any),(null as any),2,(null as any),View_LogDemo_1),
    import0.ɵdirectiveDef(12,(null as any),0,import3.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    import0.ɵpipeDef(2,import3.AsyncPipe,[import0.ChangeDetectorRef]),
    import0.ɵtextDef((null as any),['\n                ']),
    import0.ɵtextDef((null as any),['\n                ']),
    import0.ɵelementDef(0,(null as any),(null as any),2,'h4',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import0.ɵelementDef(0,(null as any),(null as any),1,'a',[[
        'href',
        'http://www.syntaxsuccess.com/viewarticle/redux-in-angular-2.0'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Read more here']),
    import0.ɵtextDef((null as any),['\n              '])
  ]
  ,(check,view) => {
    var comp:import1.LogDemo = view.component;
    const currVal_0:any = comp.msg;
    check(view,11,0,currVal_0);
    const currVal_1:any = comp.severity;
    check(view,19,0,currVal_1);
    const currVal_2:any = import0.ɵunwrapValue(import0.ɵnodeValue(view,38).transform(comp.store.logEntries));
    check(view,37,0,currVal_2);
  },(check,view) => {
    var comp:import1.LogDemo = view.component;
    const currVal_0:any = import0.ɵnodeValue(view,13).ngClassUntouched;
    const currVal_1:any = import0.ɵnodeValue(view,13).ngClassTouched;
    const currVal_2:any = import0.ɵnodeValue(view,13).ngClassPristine;
    const currVal_3:any = import0.ɵnodeValue(view,13).ngClassDirty;
    const currVal_4:any = import0.ɵnodeValue(view,13).ngClassValid;
    const currVal_5:any = import0.ɵnodeValue(view,13).ngClassInvalid;
    const currVal_6:any = import0.ɵnodeValue(view,13).ngClassPending;
    check(view,8,0,currVal_0,currVal_1,currVal_2,currVal_3,currVal_4,currVal_5,currVal_6);
    const currVal_7:any = import0.ɵnodeValue(view,21).ngClassUntouched;
    const currVal_8:any = import0.ɵnodeValue(view,21).ngClassTouched;
    const currVal_9:any = import0.ɵnodeValue(view,21).ngClassPristine;
    const currVal_10:any = import0.ɵnodeValue(view,21).ngClassDirty;
    const currVal_11:any = import0.ɵnodeValue(view,21).ngClassValid;
    const currVal_12:any = import0.ɵnodeValue(view,21).ngClassInvalid;
    const currVal_13:any = import0.ɵnodeValue(view,21).ngClassPending;
    check(view,15,0,currVal_7,currVal_8,currVal_9,currVal_10,currVal_11,currVal_12,currVal_13);
  });
}
const RenderType_LogDemo_Host:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {animation: ([] as any[])}
}
);
function View_LogDemo_Host_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),3,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_LogDemo_0,RenderType_LogDemo),
    import0.ɵproviderDef(0,(null as any),1,import4.Store,import4.Store,([] as any[])),
    import0.ɵproviderDef(0,(null as any),1,import5.LogTailService,import5.LogTailService,[import6.Http]),
    import0.ɵdirectiveDef(1025,(null as any),0,import1.LogDemo,[
      import4.Store,
      import5.LogTailService
    ]
    ,(null as any),(null as any))
  ]
  ,(check,view) => {
    check(view,3,0);
  },(null as any));
}
export const LogDemoNgFactory:import0.ComponentFactory<import1.LogDemo> = import0.ɵcreateComponentFactory('ng-component',import1.LogDemo,View_LogDemo_Host_0);