/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './comment-section-1.ngfactory';
import * as import2 from '../../../components/change-detection/comment-section-1';
import * as import3 from './comment-section-2.ngfactory';
import * as import4 from '../../../components/change-detection/comment-section-2';
import * as import5 from '../../../components/change-detection/comment-demo';
const styles_CommentDemo:any[] = ([] as any[]);
export const RenderType_CommentDemo:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: styles_CommentDemo,
  data: {animation: ([] as any[])}
}
);
export function View_CommentDemo_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Change Detection']),
    import0.ɵtextDef((null as any),['\n']),
      import0.ɵelementDef(0,(null as any),(null as any),13,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n    ']),
      import0.ɵelementDef(0,(null as any),(null as any),4,'div',[[
        'class',
        'col-md-6'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n\n        ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'comment-section-1',([] as any[]),(null as any),(null as any),(null as any),import1.View_CommentSection1_0,import1.RenderType_CommentSection1),
    import0.ɵdirectiveDef(1024,(null as any),0,import2.CommentSection1,([] as any[]),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n    ']),
    import0.ɵtextDef((null as any),['\n\n    ']),
      import0.ɵelementDef(0,(null as any),(null as any),4,'div',[[
        'class',
        'col-md-6'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n        ']),
    import0.ɵelementDef(0,(null as any),(null as any),1,'comment-section-2',([] as any[]),(null as any),(null as any),(null as any),import3.View_CommentSection2_0,import3.RenderType_CommentSection2),
    import0.ɵdirectiveDef(1024,(null as any),0,import4.CommentSection2,([] as any[]),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n    ']),
    import0.ɵtextDef((null as any),['\n']),
    import0.ɵtextDef((null as any),['\n']),
      import0.ɵelementDef(0,(null as any),(null as any),11,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n    ']),
      import0.ɵelementDef(0,(null as any),(null as any),8,'div',[[
        'style',
        'margin: 15px;'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['\n        ']),
      import0.ɵelementDef(0,(null as any),(null as any),1,'button',([] as any[]),(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import5.CommentDemo = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>comp.count()) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Increment Counter']),
    import0.ɵtextDef((null as any),['\n        ']),
    import0.ɵelementDef(0,(null as any),(null as any),2,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵelementDef(0,(null as any),(null as any),1,'strong',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),[
      '',
      ''
    ]
    ),
    import0.ɵtextDef((null as any),['\n    ']),
    import0.ɵtextDef((null as any),['\n']),
    import0.ɵtextDef((null as any),['\n']),
    import0.ɵelementDef(0,(null as any),(null as any),2,'h4',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import0.ɵelementDef(0,(null as any),(null as any),1,'a',[[
        'href',
        'http://www.syntaxsuccess.com/viewarticle/change-detection-in-angular-2.0'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import0.ɵtextDef((null as any),['Read more here'])
  ]
  ,(null as any),(check,view) => {
    var comp:import5.CommentDemo = view.component;
    const currVal_0:any = comp.counter;
    check(view,27,0,currVal_0);
  });
}
const RenderType_CommentDemo_Host:import0.RendererTypeV2 = import0.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {animation: ([] as any[])}
}
);
function View_CommentDemo_Host_0():import0.ɵViewDefinition {
  return import0.ɵviewDef(0,[
    import0.ɵelementDef(0,(null as any),(null as any),1,'comment-demo',([] as any[]),(null as any),(null as any),(null as any),View_CommentDemo_0,RenderType_CommentDemo),
    import0.ɵdirectiveDef(1024,(null as any),0,import5.CommentDemo,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const CommentDemoNgFactory:import0.ComponentFactory<import5.CommentDemo> = import0.ɵcreateComponentFactory('comment-demo',import5.CommentDemo,View_CommentDemo_Host_0);