/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../components/jquery-integration/jquery-integration';
const styles_JqueryIntegration:any[] = ([] as any[]);
export const RenderType_JqueryIntegration:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_JqueryIntegration,
  data: {}
}
);
export function View_JqueryIntegration_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Integrating jQuery with Angular 2.0'])),
    (l()(),import0.ɵted((null as any),['\n\n'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'div',[[
        'class',
        'moving-box'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    Drag this box around\n'])),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'h4',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'a',[[
        'href',
        'http://www.syntaxsuccess.com/viewarticle/using-jquery-with-angular-2.0'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Read more here']))
  ]
  ,(null as any),(null as any));
}
function View_JqueryIntegration_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'jquery-integration',([] as any[]),(null as any),(null as any),(null as any),View_JqueryIntegration_0,RenderType_JqueryIntegration)),
    import0.ɵdid(114688,(null as any),0,import1.JqueryIntegration,[import0.ElementRef],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const JqueryIntegrationNgFactory:import0.ComponentFactory<import1.JqueryIntegration> = import0.ɵccf('jquery-integration',import1.JqueryIntegration,View_JqueryIntegration_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3Rvci9EZXZlbG9wbWVudC9hbmd1bGFyLTItc2FtcGxlcy9jb21wb25lbnRzL2pxdWVyeS1pbnRlZ3JhdGlvbi9qcXVlcnktaW50ZWdyYXRpb24ubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvdG9yL0RldmVsb3BtZW50L2FuZ3VsYXItMi1zYW1wbGVzL2NvbXBvbmVudHMvanF1ZXJ5LWludGVncmF0aW9uL2pxdWVyeS1pbnRlZ3JhdGlvbi50cyIsIm5nOi8vL1VzZXJzL3Rvci9EZXZlbG9wbWVudC9hbmd1bGFyLTItc2FtcGxlcy9jb21wb25lbnRzL2pxdWVyeS1pbnRlZ3JhdGlvbi9qcXVlcnktaW50ZWdyYXRpb24uaHRtbCIsIm5nOi8vL1VzZXJzL3Rvci9EZXZlbG9wbWVudC9hbmd1bGFyLTItc2FtcGxlcy9jb21wb25lbnRzL2pxdWVyeS1pbnRlZ3JhdGlvbi9qcXVlcnktaW50ZWdyYXRpb24udHMuSnF1ZXJ5SW50ZWdyYXRpb25fSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+SW50ZWdyYXRpbmcgalF1ZXJ5IHdpdGggQW5ndWxhciAyLjA8L2gxPlxuXG48ZGl2IGNsYXNzPVwibW92aW5nLWJveFwiPlxuICAgIERyYWcgdGhpcyBib3ggYXJvdW5kXG48L2Rpdj5cblxuPGg0PjxhIGhyZWY9XCJodHRwOi8vd3d3LnN5bnRheHN1Y2Nlc3MuY29tL3ZpZXdhcnRpY2xlL3VzaW5nLWpxdWVyeS13aXRoLWFuZ3VsYXItMi4wXCI+UmVhZCBtb3JlIGhlcmU8L2E+PC9oND4iLCI8anF1ZXJ5LWludGVncmF0aW9uPjwvanF1ZXJ5LWludGVncmF0aW9uPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJO0lBQXdDO01BRTVDO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBd0I7SUFFbEI7SUFFTjtNQUFJO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBaUY7Ozs7OztJQ05yRjtnQkFBQTs7O0lBQUE7OzsifQ==
