/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../components/tree-view/tree-view-demo';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../components/tree-view/tree-view';
import * as import9 from './tree-view.ngfactory';
export class Wrapper_TreeViewDemo {
  /*private*/ _eventHandler:Function;
  context:import0.TreeViewDemo;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.TreeViewDemo();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_TreeViewDemo_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_TreeViewDemo_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.TreeViewDemo>;
  _TreeViewDemo_0_3:Wrapper_TreeViewDemo;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TreeViewDemo_Host0,renderType_TreeViewDemo_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_TreeViewDemo0(this.viewUtils,this,0,this._el_0);
    this._TreeViewDemo_0_3 = new Wrapper_TreeViewDemo();
    this.compView_0.create(this._TreeViewDemo_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._TreeViewDemo_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TreeViewDemo) && (0 === requestNodeIndex))) { return this._TreeViewDemo_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TreeViewDemo_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const TreeViewDemoNgFactory:import7.ComponentFactory<import0.TreeViewDemo> = new import7.ComponentFactory<import0.TreeViewDemo>('ng-component',View_TreeViewDemo_Host0,import0.TreeViewDemo);
const styles_TreeViewDemo:any[] = ([] as any[]);
var renderType_TreeViewDemo:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_TreeViewDemo,{});
export class View_TreeViewDemo0 extends import1.AppView<import0.TreeViewDemo> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import8.TreeView>;
  _TreeView_2_3:import9.Wrapper_TreeView;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TreeViewDemo0,renderType_TreeViewDemo,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Recursive TreeView',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,parentRenderNode,'tree-view',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import9.View_TreeView0(this.viewUtils,this,2,this._el_2);
    this._TreeView_2_3 = new import9.Wrapper_TreeView();
    this.compView_2.create(this._TreeView_2_3.context);
    this._text_3 = this.renderer.createText(parentRenderNode,'          ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,parentRenderNode,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_4,'a',new import3.InlineArray2(2,'href','http://www.syntaxsuccess.com/viewarticle/recursive-treeview-in-angular-2.0'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Read more here',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import8.TreeView) && (2 === requestNodeIndex))) { return this._TreeView_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.context.directories;
    this._TreeView_2_3.check_directories(currVal_2_0_0,throwOnChange,false);
    this._TreeView_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this.compView_2.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
  }
}